#!/usr/bin/env bash
set -euo pipefail

python scripts/make_figure_1_mouse_habenula_atlas.py
python scripts/make_figure_2_mouse_differential_expression.py
python scripts/make_figure_5_yalcinbas_lhb_mapping.py
python scripts/make_figure_5_yalcinbas_mhb_mapping.py
python scripts/make_figure_5_yalcinbas_sensitivity.py
python scripts/make_figure_5_yalcinbas_summary.py
python scripts/make_figure_5_kim_region_enrichment.py
python scripts/make_figure_5_kim_celltype_enrichment.py
